language: cpp
dist: trusty
sudo: required

notifications:
  email: false

addons:
  apt:
    sources:
#       - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9 
    packages: ['portaudio19-dev', 'libfftw3-dev', 'libasound2-dev', 'libjack-dev', 'libboost-dev', 
#     'gcc-4.9', 'g++-4.9',
'clang-3.9','libc++-dev','libc++abi-dev',
#  'libglfw3', 'libglfw3-dev'
'xorg-dev'
]

matrix:
  include:
#     - os: linux
#       compiler: gcc
#       env:
#         - COVERAGE=1
#         - DOXYGEN
#         - EXTRA_FLAGS="-stdlib=libc++"
    - os: linux
      compiler: clang
      env:
        - COVERAGE=1
        - DOXYGEN
        - EXTRA_FLAGS="-stdlib=libc++"
        - LIBCXX=On

before_install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
  - if [[ $CXX = g++ ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang has a conflict with gcc, so use clang-X.Y.
  - if [[ $CXX = clang++ ]]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - chmod +x ./config/script.sh
  - git clone --depth=50 --branch=master https://github.com/njazz/imgui-mvc-wrap.git /home/travis/build/njazz/imgui
  - mkdir glfw && cd glfw
  - git clone https://github.com/glfw/glfw && mkdir build && cd build  
  - git cmake ../glfw && make -j4 
  - sudo make install
  - cd ../..
script:
  - ./config/script.sh
